### ISSUE TITLE
Something about the size of SVT-Perspective dataset

### ISSUE THREAD

**Issue by smilewsw** [chengzhanzhan/STR#1]
In the paper "AON: Towards Arbitrarily-Oriented Text Recognition" and other papers about irregular text recognition,  SVT-P dataset contains 639 cropped test images. But in your repository, there are 645 cropped samples in SVT-Perspective testing set. Is something wrong?  By the way, would you please provide the corresponding lexicons of these data? Waiting for your reply. Thanks.

**Comment by chengzhanzhan** [comment]
SVT-P (readme) declare there're 639 cropped images from the origin image; but we crop and count, get 645 (the version we used) images.
As to the lexicons, you can generate them based the corresponding'lexicon-generation' rule.
